import express, { Request, Response } from 'express';
import crypto from 'crypto';
import { config } from 'dotenv';
import { GitHubClient } from './github';
import { LLMClient } from './llm';
import { shouldSkipPR, categorizeFiles } from './skip';
import { PullRequestInfo } from './types';

config();

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;
const WEBHOOK_SECRET = process.env.GITHUB_WEBHOOK_SECRET || '';

function verifyWebhookSignature(req: Request): boolean {
  const signature = req.headers['x-hub-signature-256'] as string;
  if (!signature || !WEBHOOK_SECRET) return false;

  const hmac = crypto.createHmac('sha256', WEBHOOK_SECRET);
  const digest = 'sha256=' + hmac.update(JSON.stringify(req.body)).digest('hex');
  return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(digest));
}

app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

app.post('/webhook', async (req: Request, res: Response) => {
  if (WEBHOOK_SECRET && !verifyWebhookSignature(req)) {
    res.status(401).json({ error: 'Invalid signature' });
    return;
  }

  const event = req.headers['x-github-event'] as string;
  const payload = req.body;

  if (event !== 'pull_request') {
    res.json({ message: 'Ignored event', event });
    return;
  }

  const action = payload.action;
  if (!['opened', 'synchronize', 'reopened'].includes(action)) {
    res.json({ message: 'Ignored action', action });
    return;
  }

  res.json({ message: 'Processing' });

  try {
    await processPullRequest(payload);
  } catch (error) {
    console.error('Error processing PR:', error);
  }
});

async function processPullRequest(payload: {
  pull_request: {
    number: number;
    title: string;
    body: string | null;
    base: { sha: string; repo: { owner: { login: string }; name: string } };
    head: { sha: string };
    labels: Array<{ name: string }>;
  };
  repository: { owner: { login: string }; name: string };
  installation?: { id: number };
}) {
  const githubToken = process.env.GITHUB_TOKEN;
  const anthropicKey = process.env.ANTHROPIC_API_KEY;

  if (!githubToken || !anthropicKey) {
    console.error('Missing required environment variables');
    return;
  }

  const github = new GitHubClient(githubToken);
  const llm = new LLMClient(anthropicKey);

  const owner = payload.repository.owner.login;
  const repo = payload.repository.name;
  const pullNumber = payload.pull_request.number;

  console.log(`Processing PR #${pullNumber} in ${owner}/${repo}`);

  const pr: PullRequestInfo = {
    owner,
    repo,
    number: pullNumber,
    title: payload.pull_request.title,
    body: payload.pull_request.body,
    base: payload.pull_request.base.sha,
    head: payload.pull_request.head.sha,
    labels: payload.pull_request.labels.map(l => l.name),
  };

  const diff = await github.getPRDiff(owner, repo, pullNumber);

  const skipCheck = shouldSkipPR(pr, diff);
  if (skipCheck.shouldSkip) {
    console.log(`Skipping PR #${pullNumber}: ${skipCheck.reason}`);
    return;
  }

  const categories = categorizeFiles(diff);
  console.log(`Files: ${categories.source.length} source, ${categories.tests.length} tests, ${categories.docs.length} docs`);

  const docs = await llm.generatePRSummary(diff, pr.title);

  let comment = `## PR Summary (AI Generated)\n\n${docs.prSummary}`;

  if (docs.readmeChanges) {
    comment += `\n\n---\n\n### README追記候補\n\n\`\`\`markdown\n${docs.readmeChanges}\n\`\`\``;
  }

  const adr = await llm.generateADR(diff, pr.title, pr.body);
  if (adr) {
    comment += `\n\n---\n\n### ADRドラフト\n\n<details>\n<summary>クリックして展開</summary>\n\n${adr}\n\n</details>`;
  }

  comment += '\n\n---\n*Generated by diff-note*';

  await github.postPRComment(owner, repo, pullNumber, comment);
  console.log(`Posted comment to PR #${pullNumber}`);
}

app.listen(PORT, () => {
  console.log(`diff-note server running on port ${PORT}`);
});
